library(car)
library(gmodels)
library(lme4)
library(lubridate)
library(MASS)
library(nlme)
library(plyr)
library(reshape2)
library(reshape)
library(xlsx)
library(contrast)
library(effects)
library(ggplot2)
library(scales)
library(xtable)
library(visreg)
library(lmerTest)
library(gridExtra)
library(foreach)
library(doParallel) # set up parallel backend for foreach
library(snow) # require to difine makeCluster for foreach
library(doSNOW)
library(grid)
library(quantmod) # compute % change
library(boot)

install.packages("devtools")
require(devtools)
install_github("hadley/ggplot2") 
